#!/bin/bash

docker rm manim_ce
docker run -it \
--name manim_ce \
-p 0.0.0.0:8888:8888 \
-v $(pwd)/notebooks:/manim/notebooks \
manim_ce_i \
jupyter lab --notebook-dir='./notebooks' --no-browser --ip=0.0.0.0 --port=8888 
