#!/bin/bash

docker build -t manimi ./ 
docker rm manim
docker run -it \
--name manim \
-p 0.0.0.0:8888:8888 \
-v $(pwd)/notebooks:/manim/notebooks \
manimi \
jupyter lab --notebook-dir='./notebooks' --no-browser --ip=0.0.0.0 --port=8888 
