#!/bin/bash

docker run -it \
-p 0.0.0.0:8888:8888 \
-v $(pwd)/notebooks:/app/notebooks \
-v $(pwd)/src:/app/src \
manim_ce_i \
pip install -e . && jupyter lab --notebook-dir='./notebooks' --no-browser --ip=0.0.0.0 --port=8888 
